# Generated by Django 4.2.28 on 2026-03-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_news_image_to_imagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Предмет / направление')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в каталоге')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['full_name'],
            },
        ),
    ]
