# Generated by Django 4.2.28 on 2026-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_teacher_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Якорь (slug)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на странице')),
            ],
            options={
                'verbose_name': 'Раздел (сведения)',
                'verbose_name_plural': 'Разделы (сведения об организации)',
                'ordering': ['order'],
            },
        ),
    ]
