# Generated by Django 4.2.28 on 2026-03-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_education_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Якорь (для навигации)')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое (HTML)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел (контакты)',
                'verbose_name_plural': 'Разделы (контакты и сведения)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='contacts_docs/%Y/%m/', verbose_name='Файл')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.contactsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Документ (контакты)',
                'verbose_name_plural': 'Документы (контакты)',
            },
        ),
    ]
