# Generated by Django 4.2.28 on 2026-03-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_add_contact_section_and_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationSection',
        ),
    ]
