# Generated by Django 4.2.28 on 2026-03-01 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_add_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен подтверждения'),
        ),
    ]
