# Generated by Django 4.2.30 on 2026-04-30 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_alter_groupcourserequest_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["created_at", "title"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="groupcourserequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка на групповой курс",
                "verbose_name_plural": "Заявки на групповые курсы",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Создана",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("mini", "Mini-group (up to 6 students)"),
                    ("standard", "Standard group"),
                    ("intensive", "Intensive"),
                ],
                max_length=20,
                verbose_name="Тип группы",
            ),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Обработано"),
        ),
        migrations.AlterField(
            model_name="groupcourserequest",
            name="schedule",
            field=models.CharField(
                choices=[
                    ("2_per_week", "2 times per week"),
                    ("3_per_week", "3 times per week"),
                    ("daily", "Intensive (daily)"),
                ],
                max_length=20,
                verbose_name="Расписание",
            ),
        ),
    ]
