"""
Django settings for wunder project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv():
    """Load .env file into os.environ if present. No extra dependency."""
    env_file = BASE_DIR / ".env"
    if not env_file.exists():
        return
    with open(env_file, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip("'\"")
                if key and key not in os.environ:
                    os.environ[key] = value


_load_dotenv()


def get_env(key, default=None, required=False):
    """Read env var; raise ImproperlyConfigured if required and missing."""
    value = os.environ.get(key, default)
    if required and (value is None or value == ""):
        raise ImproperlyConfigured(
            f"Set the {key} environment variable. "
            f"Add it to .env or export it before running the application."
        )
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env("DJANGO_SECRET_KEY", required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

_default_hosts = ["localhost", "127.0.0.1"]
_env_hosts = [h.strip() for h in get_env("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
ALLOWED_HOSTS = _env_hosts if _env_hosts else _default_hosts

# CSRF: origins that are allowed to make cross-origin requests (scheme + host required)
# Required in Django 4.0+ when Origin/Referer differ from request host (e.g. proxy, alternate port)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]
# Append any extra origins from env (comma-separated, e.g. https://mysite.com)
_extra_csrf = get_env("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in _extra_csrf.split(",") if o.strip()])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ckeditor",
    "core",
    "pages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "wunder.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pages.context_processors.subscribe_form",
                "pages.context_processors.application_form",
            ],
        },
    },
]

WSGI_APPLICATION = "wunder.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_db_engine = get_env("DJANGO_DB_ENGINE", "").lower()

if _db_engine == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": get_env("POSTGRES_DB", "wunder"),
            "USER": get_env("POSTGRES_USER", ""),
            "PASSWORD": get_env("POSTGRES_PASSWORD", ""),
            "HOST": get_env("POSTGRES_HOST", "localhost"),
            "PORT": get_env("POSTGRES_PORT", "5432"),
            "OPTIONS": {"sslmode": get_env("POSTGRES_SSLMODE", "prefer")},
        }
    }
else:
    _sqlite_path = get_env("DJANGO_DB_PATH", "db.sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / _sqlite_path if not os.path.isabs(_sqlite_path) else _sqlite_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = get_env("DJANGO_LANGUAGE_CODE", "ru")

TIME_ZONE = get_env("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = get_env("DJANGO_STATIC_ROOT", "") or None
if STATIC_ROOT:
    STATIC_ROOT = Path(STATIC_ROOT)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Optional: API keys and secrets (from env only) ---

# reCAPTCHA (for server-side verification if used)
RECAPTCHA_SECRET_KEY = get_env("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_SITE_KEY = get_env("RECAPTCHA_SITE_KEY", "")

# Email (optional)
EMAIL_BACKEND = get_env(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = get_env("EMAIL_HOST", "")
EMAIL_PORT = get_env("EMAIL_PORT", "587")
EMAIL_USE_TLS = get_env("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = get_env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_env("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = get_env("DEFAULT_FROM_EMAIL", "noreply@example.com")

# --- Медиа (загрузки): для localhost — папка media в корне проекта ---
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
